services:
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native 
    volumes:
      - ./:/app
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    devices:
      - /dev/snd:/dev/snd
    privileged: true